[env:m5stick-c-plus2]
platform = espressif32
board = m5stick-c-plus2
framework = arduino
monitor_speed = 115200
upload_port = COM6
monitor_port = COM6
board_build.partitions = default_8MB.csv
lib_deps =
    m5stack/M5StickCPlus2 @ ^1.0.2
    hijelhub/HijelHID_BLEKeyboard @ ^0.3.1
